# Generated by Django 3.2.3 on 2021-07-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210731_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': ('user',), 'verbose_name_plural': 'Пользователи'},
        ),
    ]
