# Generated by Django 3.2.3 on 2021-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210731_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=True, max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
