# Generated by Django 3.2.3 on 2021-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210813_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(max_length=300, null=True, verbose_name='Адрес отгрузки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='org',
            field=models.TextField(max_length=150, null=True, verbose_name='Наименование организации'),
        ),
    ]
