# Generated by Django 3.2.3 on 2021-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purse',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Кошелек'),
        ),
    ]
