# Generated by Django 3.2.3 on 2021-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_purse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cashback',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Кешбэк'),
        ),
    ]
