# Generated by Django 3.2.3 on 2021-11-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customuser_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_office',
            field=models.TextField(max_length=300, null=True, verbose_name='Адрес-Офис'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_rod',
            field=models.TextField(max_length=300, null=True, verbose_name='Адрес-Родители'),
        ),
    ]
