# Generated by Django 3.2.3 on 2021-06-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210613_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
