# Generated by Django 3.2.3 on 2021-09-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_city', models.JSONField(blank=True, default=list, null=True)),
                ('category_city', models.JSONField(blank=True, default=list, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Территория продаж')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Активный')),
                ('customuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Территория продаж',
                'verbose_name_plural': 'Территории продаж',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.JSONField(blank=True, default=list, null=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d', verbose_name='Изображение')),
                ('status', models.BooleanField(default=True, verbose_name='Активный')),
                ('descriptions', models.TextField(max_length=300, null=True, verbose_name='Описание категории')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.area', verbose_name='Территория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory/%Y/%m/%d', verbose_name='Изображение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегория',
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название магазина')),
                ('status', models.BooleanField(default=True, verbose_name='Статус активный')),
                ('descriptions', models.TextField(db_index=True, max_length=500, null=True, verbose_name='Описание')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.area', verbose_name='Территория')),
                ('customuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название населенного пункта')),
                ('delivery_price', models.PositiveIntegerField(null=True, verbose_name='Цена доставки')),
                ('delivery_price_min', models.PositiveIntegerField(null=True, verbose_name='минимальная цена доставки')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'День недели',
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.locations', verbose_name='Населенный пункт'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название продукта')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True, verbose_name='Описания продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Склад')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Подкатегория', to='panel.subcategory')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
        migrations.AlterIndexTogether(
            name='area',
            index_together={('id', 'slug')},
        ),
    ]
