# Generated by Django 4.0.3 on 2022-08-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files',
        ),
    ]
