# Generated by Django 4.0.3 on 2022-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_delete_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название файла')),
                ('slug', models.SlugField(max_length=200, null=True, verbose_name='Магазин')),
                ('fileart', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Файл выгрузки товаров')),
            ],
            options={
                'verbose_name': 'Файловая обработка',
                'verbose_name_plural': 'Файловая обработка',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
