# Generated by Django 4.0.3 on 2022-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='Дата загрузки'),
        ),
    ]
