# Generated by Django 3.2.3 on 2021-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_locations_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='days',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='День недели'),
        ),
    ]
