# Generated by Django 3.2.3 on 2021-09-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_locations_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='days',
        ),
    ]
