# Generated by Django 4.0.3 on 2022-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_files_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='time',
            field=models.TimeField(auto_now=True, db_index=True, verbose_name='Время загрузки'),
        ),
    ]
