# Generated by Django 4.0.3 on 2022-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_files_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='org',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Организация'),
        ),
    ]
