# Generated by Django 3.2.3 on 2021-09-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_locations_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descriptions',
        ),
    ]
