# Generated by Django 4.0.3 on 2022-08-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_subcategory_subcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcat',
        ),
    ]
