# Generated by Django 3.2.3 on 2021-09-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.FloatField(blank=True, null=True, verbose_name='Номер'),
        ),
    ]
