# Generated by Django 4.0.3 on 2022-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_remove_subcategory_subcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название лога')),
                ('slug', models.SlugField(max_length=200, null=True, verbose_name='Магазин')),
                ('fileart', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Файл выгрузки товаров')),
                ('date', models.DateField(auto_now=True, db_index=True, verbose_name='Дата загрузки')),
                ('time', models.TimeField(auto_now=True, db_index=True, verbose_name='Время загрузки')),
                ('org', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Организация')),
                ('list_update', models.JSONField(blank=True, default=list, null=True, verbose_name='Обновленные позиции')),
            ],
            options={
                'verbose_name': 'Логи файловой обработки',
                'verbose_name_plural': 'Логи Файловой обработки',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
