# Generated by Django 4.0.3 on 2022-08-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
