# Generated by Django 4.0.3 on 2022-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpdesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название заявки')),
                ('name_user', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Пользователь')),
                ('slug', models.SlugField(max_length=200, null=True, verbose_name='Магазин')),
                ('date', models.DateField(auto_now=True, db_index=True, verbose_name='Дата создания')),
                ('time', models.TimeField(auto_now=True, db_index=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Служба поддержки',
                'verbose_name_plural': 'Служба поддержки',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
