# Generated by Django 4.0.3 on 2022-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_helpdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='descriptions',
            field=models.TextField(db_index=True, max_length=10000, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
