# Generated by Django 3.2.3 on 2021-09-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер'),
        ),
    ]
