# Generated by Django 4.0.3 on 2022-09-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_helpdesk_descriptions_helpdesk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='name_user_help',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Специалист по обработке заявки'),
        ),
    ]
