# Generated by Django 3.2.3 on 2021-09-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20210914_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='number',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Номер'),
        ),
    ]
