# Generated by Django 4.0.3 on 2022-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_helpdesk_name_user_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='descriptions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='helpdesk',
            name='status',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Статус'),
        ),
    ]
