# Generated by Django 3.2.3 on 2021-09-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_alter_subcategory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='number',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
