# Generated by Django 4.0.3 on 2022-09-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_helpdesk_descriptions_alter_helpdesk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='helpdeskfile/', verbose_name='Скриншот'),
        ),
    ]
