# Generated by Django 3.2.3 on 2021-09-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_subcategory_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='number',
        ),
    ]
