# Generated by Django 4.0.3 on 2022-09-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_helpdesk_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='helpdesk',
        ),
    ]
