# Generated by Django 3.2.3 on 2021-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_subcategory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='number',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Номер'),
        ),
    ]
