# Generated by Django 4.0.3 on 2022-09-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_helpdesk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpDesk',
        ),
    ]
