# Generated by Django 4.0.3 on 2022-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_helpdesk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk_user',
            name='org',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Организация'),
        ),
    ]
