# Generated by Django 4.0.3 on 2022-09-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_helpdesk_user_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk_user',
            name='email_user',
            field=models.SlugField(max_length=200, null=True, verbose_name='Email'),
        ),
    ]
