# Generated by Django 4.0.3 on 2022-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_alter_helpdesk_user_name_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdesk_user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='helpdesk_user',
            name='time',
        ),
        migrations.AddField(
            model_name='helpdesk_user',
            name='date_time',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Дата создания и время'),
        ),
    ]
