# Generated by Django 4.0.3 on 2022-11-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_bisert'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='time',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Время платной доставки'),
        ),
        migrations.AddField(
            model_name='locations',
            name='time_price_delivery',
            field=models.PositiveIntegerField(null=True, verbose_name='Стоимость доставки по времени'),
        ),
    ]
