# Generated by Django 4.0.3 on 2022-11-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_locations_time_locations_time_price_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='time',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='time_price_delivery',
        ),
    ]
