# Generated by Django 3.2.3 on 2021-09-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_auto_20210915_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcat',
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.subcategory', verbose_name='Товарная группа'),
        ),
    ]
