# Generated by Django 3.2.3 on 2021-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_auto_20210915_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
