# Generated by Django 4.0.3 on 2022-11-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_locations_days_numb_dop_locations_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='time',
        ),
    ]
