# Generated by Django 3.2.3 on 2021-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_auto_20210915_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
    ]
