# Generated by Django 3.2.3 on 2021-09-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
