# Generated by Django 4.0.3 on 2022-11-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_remove_locations_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='time_end',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Время платной доставки конец'),
        ),
        migrations.AddField(
            model_name='locations',
            name='time_start',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Время платной доставки начало'),
        ),
    ]
