# Generated by Django 3.2.3 on 2021-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_auto_20210917_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
