# Generated by Django 3.2.3 on 2021-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
