# Generated by Django 4.0.3 on 2022-11-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_natalinsk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='time_price_delivery',
        ),
    ]
