# Generated by Django 3.2.3 on 2021-09-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
