# Generated by Django 3.2.3 on 2021-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_remove_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
