# Generated by Django 4.0.3 on 2022-12-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0034_orders_sbp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='sbp',
            field=models.BooleanField(default=False, verbose_name='SBP'),
        ),
    ]
