# Generated by Django 4.0.3 on 2022-12-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0035_alter_orders_sbp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='sbp',
        ),
    ]
