# Generated by Django 3.2.3 on 2021-09-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0035_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('number', models.FloatField(blank=True, null=True, verbose_name='Номер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Подподкатегория',
                'verbose_name_plural': 'Подподкатегория',
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
    ]
