# Generated by Django 3.2.3 on 2021-09-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0036_subsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Товарная подгруппа'),
        ),
    ]
