# Generated by Django 4.0.3 on 2022-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0036_remove_orders_sbp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sbp',
            field=models.BooleanField(default=False, verbose_name='SBP'),
        ),
    ]
