# Generated by Django 3.2.3 on 2021-10-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_rezh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rezh',
        ),
    ]
