# Generated by Django 4.0.3 on 2022-12-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_shop_sbp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='qr_code',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='QR код'),
        ),
    ]
