# Generated by Django 4.0.3 on 2022-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0039_shop_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='artiobschepit',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='bisert',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='bugalysh',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='chernovskoe',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='krasnoufimsk',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='natalinsk',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='pokrovskoe',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='zajkovskoe',
            name='count',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Кол-во'),
        ),
    ]
