# Generated by Django 3.2.3 on 2021-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_rezh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezh',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rezh/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
