# Generated by Django 4.0.3 on 2023-01-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_arti_count_arti_p_count_artiobschepit_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='category_city',
        ),
        migrations.RemoveField(
            model_name='area',
            name='local_city',
        ),
        migrations.RemoveField(
            model_name='area',
            name='location',
        ),
        migrations.DeleteModel(
            name='offers',
        ),
    ]
