# Generated by Django 3.2.3 on 2021-10-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0041_alter_rezh_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rezh',
        ),
    ]
