# Generated by Django 4.0.3 on 2023-01-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0042_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
