# Generated by Django 3.2.3 on 2021-10-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0043_rezh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezh',
            options={'ordering': ('name',), 'verbose_name': 'Реж', 'verbose_name_plural': 'Продукты'},
        ),
    ]
