# Generated by Django 4.0.3 on 2023-01-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0044_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
