# Generated by Django 3.2.3 on 2021-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0046_arti_bogdan'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name_id',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
