# Generated by Django 3.2.3 on 2021-10-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0047_auto_20211003_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arti',
        ),
        migrations.DeleteModel(
            name='Bogdan',
        ),
        migrations.DeleteModel(
            name='Rezh',
        ),
    ]
