# Generated by Django 3.2.3 on 2021-10-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0051_arti_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezh',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.shop', verbose_name='Магазин'),
        ),
    ]
