# Generated by Django 3.2.3 on 2021-10-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0052_rezh_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.shop', verbose_name='Магазин'),
        ),
    ]
