# Generated by Django 4.0.3 on 2023-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0053_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='file_upload/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.DeleteModel(
            name='shalinsk',
        ),
    ]
