# Generated by Django 4.0.3 on 2023-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0054_alter_files_fileart_delete_shalinsk'),
    ]

    operations = [
        migrations.CreateModel(
            name='no_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, null=True, verbose_name='Магазин')),
                ('date', models.DateField(auto_now=True, db_index=True, verbose_name='Дата загрузки')),
                ('org', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Необработанная выгрузка',
                'verbose_name_plural': 'Необработанная выгрузка',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
