# Generated by Django 3.2.3 on 2021-10-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0054_shalinsk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shalinsk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shalinsk/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
