# Generated by Django 4.0.3 on 2023-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0055_no_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='no_product',
            name='list_product',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Список товаров'),
        ),
    ]
