# Generated by Django 3.2.3 on 2021-10-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0055_alter_shalinsk_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название заказа')),
                ('data', models.DateField(auto_now=True, db_index=True, verbose_name='Дата заказа')),
                ('time', models.TimeField(auto_now=True, db_index=True, verbose_name='Время заказа')),
            ],
            options={
                'verbose_name': 'Заках',
                'verbose_name_plural': 'Закуаз',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
