# Generated by Django 4.0.3 on 2023-02-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0056_no_product_list_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='no_product',
            name='file_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id Файла'),
        ),
    ]
