# Generated by Django 3.2.3 on 2021-10-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0056_zakaz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaz',
            options={'ordering': ('name',), 'verbose_name': 'Заках', 'verbose_name_plural': 'Заказ'},
        ),
    ]
