# Generated by Django 4.0.3 on 2023-02-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0057_no_product_file_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='no_product',
            new_name='report',
        ),
    ]
