# Generated by Django 3.2.3 on 2021-10-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0058_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offers',
        ),
        migrations.AlterModelOptions(
            name='zakaz',
            options={'ordering': ('name',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
    ]
