# Generated by Django 4.0.3 on 2023-02-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0059_remove_report_list_product_report_list_no_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('name',), 'verbose_name': 'Выгрузка', 'verbose_name_plural': 'Выгрузка'},
        ),
    ]
