# Generated by Django 3.2.3 on 2021-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0060_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.area', verbose_name='Территория'),
        ),
    ]
