# Generated by Django 4.0.3 on 2023-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0060_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TimeField(auto_now=True, db_index=True, verbose_name='Время выгрузки'),
        ),
    ]
