# Generated by Django 3.2.3 on 2021-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0061_offers_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='color',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='arti',
            name='fabricator',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='arti',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='arti',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='arti',
            name='material',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='arti',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='color',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='fabricator',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='material',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='color',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='fabricator',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='material',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='color',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='fabricator',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='material',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabricator',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='color',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='fabricator',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='material',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='color',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='fabricator',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='material',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
