# Generated by Django 4.0.3 on 2023-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0061_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
    ]
