# Generated by Django 3.2.3 on 2021-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0062_auto_20211018_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='rezh',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='subsubcat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
