# Generated by Django 4.0.3 on 2023-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0062_product_check_pres'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='artiobschepit',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='bisert',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='bugalysh',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='chernovskoe',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='krasnoufimsk',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='natalinsk',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='pokrovskoe',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='zajkovskoe',
            name='check_pres',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Наличие'),
        ),
    ]
