# Generated by Django 4.0.3 on 2023-02-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0063_arti_check_pres_arti_p_check_pres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zajkovskoe',
            name='check_pres',
        ),
    ]
