# Generated by Django 3.2.3 on 2021-10-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0063_auto_20211019_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezh',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='panel.shop', verbose_name='Магазин'),
        ),
    ]
