# Generated by Django 3.2.3 on 2021-10-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0065_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='rezh',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.shop', verbose_name='Магазин'),
        ),
    ]
