# Generated by Django 3.2.3 on 2021-10-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0066_auto_20211022_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Скидка'),
        ),
    ]
