# Generated by Django 4.0.3 on 2023-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0067_alter_zajkovskoe_check_pres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zajkovskoe',
            name='check_pres',
            field=models.CharField(max_length=200, null=True, verbose_name='Наличие'),
        ),
    ]
