# Generated by Django 3.2.3 on 2021-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0069_alter_offers_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
