# Generated by Django 3.2.3 on 2021-11-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0070_alter_offers_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='zakaz',
            new_name='orders',
        ),
    ]
