# Generated by Django 3.2.3 on 2021-11-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0071_rename_zakaz_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
