# Generated by Django 3.2.3 on 2021-11-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0074_artiobschepit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
