# Generated by Django 3.2.3 on 2021-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0077_orders_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_p',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='delivery_price_min',
            field=models.PositiveIntegerField(null=True, verbose_name='Минимальная цена доставки'),
        ),
    ]
