# Generated by Django 3.2.3 on 2021-11-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0078_auto_20211116_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customuser',
        ),
    ]
