# Generated by Django 3.2.3 on 2021-11-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0080_alter_orders_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Заказчик'),
        ),
    ]
