# Generated by Django 3.2.3 on 2021-11-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0082_alter_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.area', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(max_length=300, null=True, verbose_name='Улица и дом'),
        ),
    ]
