# Generated by Django 3.2.3 on 2021-11-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0083_auto_20211118_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.locations', verbose_name='Населенный пункт'),
        ),
    ]
