# Generated by Django 3.2.3 on 2021-11-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0084_alter_orders_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_p',
        ),
    ]
