# Generated by Django 3.2.3 on 2021-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0085_remove_orders_delivery_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_order',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена доставки'),
        ),
    ]
