# Generated by Django 3.2.3 on 2021-11-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0086_orders_total_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sum_order',
            field=models.PositiveIntegerField(null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_order',
            field=models.PositiveIntegerField(null=True, verbose_name='Общая сумма заказа'),
        ),
    ]
