# Generated by Django 3.2.3 on 2021-11-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0087_auto_20211118_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Остаток товара'),
        ),
    ]
