# Generated by Django 3.2.3 on 2021-11-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0088_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
