# Generated by Django 3.2.3 on 2021-11-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0090_zajkovskoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cal',
            field=models.TextField(max_length=300, null=True, verbose_name='Дата'),
        ),
    ]
