# Generated by Django 3.2.3 on 2021-12-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0092_pokrovskoe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiobschepit',
            options={'ordering': ('name',), 'verbose_name': 'Арти Общепит', 'verbose_name_plural': 'Арти Общепит'},
        ),
    ]
