# Generated by Django 3.2.3 on 2021-12-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0093_alter_artiobschepit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='slug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panel.area', verbose_name='Slug'),
        ),
    ]
