# Generated by Django 3.2.3 on 2021-12-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0094_locations_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='slug',
        ),
    ]
