# Generated by Django 3.2.3 on 2021-12-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0095_remove_locations_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='slug',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
