# Generated by Django 3.2.3 on 2022-01-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0096_locations_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='address_street',
        ),
    ]
