# Generated by Django 3.2.3 on 2022-01-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0097_rename_address_orders_address_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address_name',
            new_name='address_city',
        ),
    ]
