# Generated by Django 3.2.3 on 2022-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0098_rename_address_name_orders_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='days',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Дни доставки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='ogrn',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='shop',
            name='times',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='uraddress',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Юридический адрес магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название магазина'),
        ),
    ]
