# Generated by Django 3.2.3 on 2022-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0099_auto_20220118_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Сумма доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sum_order',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_order',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Общая сумма заказа'),
        ),
    ]
