# Generated by Django 3.2.3 on 2022-01-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0100_auto_20220119_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='commit',
            field=models.TextField(max_length=300, null=True, verbose_name='Коментарий'),
        ),
    ]
