# Generated by Django 3.2.3 on 2022-01-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0101_orders_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Пользователь'),
        ),
    ]
