# Generated by Django 3.2.3 on 2022-01-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0102_alter_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
