# Generated by Django 3.2.3 on 2022-01-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0103_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address_city',
            field=models.CharField(max_length=30, null=True, verbose_name='Населенный пункт'),
        ),
    ]
