# Generated by Django 3.2.3 on 2022-01-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0104_alter_orders_address_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_order',
            new_name='total_cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='total_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Общая сумма'),
        ),
    ]
