# Generated by Django 3.2.3 on 2022-01-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0105_auto_20220120_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='sum_order',
        ),
    ]
