# Generated by Django 3.2.3 on 2022-01-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0107_auto_20220122_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total',
            new_name='total_price',
        ),
    ]
