# Generated by Django 3.2.3 on 2022-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0108_rename_total_orders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Продукты в корзине'),
        ),
    ]
