# Generated by Django 3.2.3 on 2022-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0109_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Территория'),
        ),
    ]
