# Generated by Django 3.2.3 on 2022-01-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0113_orders_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='count',
        ),
    ]
