# Generated by Django 3.2.3 on 2022-01-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0115_orders_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cal',
            field=models.TextField(max_length=300, null=True, verbose_name='Дата доставки'),
        ),
    ]
