# Generated by Django 3.2.3 on 2022-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0116_alter_orders_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='daysdict',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1, null=True),
        ),
    ]
