# Generated by Django 3.2.3 on 2022-01-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0117_days_daysdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='days_numb',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Номера дней'),
        ),
    ]
