# Generated by Django 3.2.3 on 2022-01-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0118_locations_days_numb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='count',
        ),
    ]
