# Generated by Django 3.2.3 on 2022-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0120_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(max_length=30, null=True, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='orders',
            name='replace',
            field=models.CharField(max_length=30, null=True, verbose_name='Замена товара'),
        ),
    ]
