# Generated by Django 3.2.3 on 2022-02-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0121_auto_20220202_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='replace',
            field=models.CharField(max_length=50, null=True, verbose_name='Замена товара'),
        ),
    ]
