# Generated by Django 3.2.3 on 2022-02-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0122_alter_orders_replace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='replace',
            field=models.CharField(max_length=100, null=True, verbose_name='Замена товара'),
        ),
    ]
