# Generated by Django 3.2.3 on 2022-02-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0123_alter_orders_replace'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='money',
            field=models.CharField(max_length=30, null=True, verbose_name='Сумма для сдачи'),
        ),
    ]
