# Generated by Django 3.2.3 on 2022-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0124_orders_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Сумма для сдачи'),
        ),
    ]
