# Generated by Django 3.2.3 on 2022-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0126_alter_orders_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Продукты в корзине'),
        ),
    ]
