# Generated by Django 4.0.3 on 2022-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0128_alter_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='data_status',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Время обновления статуса'),
        ),
    ]
