# Generated by Django 4.0.3 on 2022-06-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0129_orders_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='artiobschepit',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='pokrovskoe',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AddField(
            model_name='zajkovskoe',
            name='categ',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Категория продукта'),
        ),
    ]
