# Generated by Django 4.0.3 on 2022-06-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0130_arti_categ_arti_p_categ_artiobschepit_categ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arti',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='arti_p',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artiobschepit',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bogdan',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chetkarino',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pokrovskoe',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rezh',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shalinsk',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zajkovskoe',
            name='subsubcat',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
