# Generated by Django 4.0.3 on 2022-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0131_alter_arti_subsubcat_alter_arti_p_subsubcat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address_city',
            field=models.CharField(max_length=300, null=True, verbose_name='Населенный пункт'),
        ),
    ]
