# Generated by Django 4.0.3 on 2022-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0133_krasnoufimsk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krasnoufimsk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='krasnoufimsk/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
