# Generated by Django 4.0.3 on 2022-07-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0135_bugalysh'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_home',
            field=models.TextField(max_length=300, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='orders',
            name='address_kv',
            field=models.TextField(max_length=300, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_street',
            field=models.TextField(max_length=300, null=True, verbose_name='Улица'),
        ),
    ]
