# Generated by Django 4.0.3 on 2022-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0136_orders_address_home_orders_address_kv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название Вакансии')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
                ('times', models.JSONField(blank=True, default=list, null=True, verbose_name='Время работы')),
                ('descriptions', models.TextField(db_index=True, max_length=500, null=True, verbose_name='Описание вакансии')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
