# Generated by Django 4.0.3 on 2022-07-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0138_work_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Магазин'),
        ),
    ]
