# Generated by Django 4.0.3 on 2022-07-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0139_work_status_alter_work_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='descriptions',
            field=models.TextField(db_index=True, max_length=10000, null=True, verbose_name='Описание вакансии'),
        ),
    ]
