# Generated by Django 4.0.3 on 2022-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0140_alter_work_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='times',
        ),
        migrations.AddField(
            model_name='work',
            name='times_end',
            field=models.CharField(max_length=30, null=True, verbose_name='Время работы конец'),
        ),
        migrations.AddField(
            model_name='work',
            name='times_start',
            field=models.CharField(max_length=30, null=True, verbose_name='Время работы начало'),
        ),
    ]
