# Generated by Django 4.0.3 on 2022-07-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0141_remove_work_times_work_times_end_work_times_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='work',
            new_name='works',
        ),
    ]
