# Generated by Django 4.0.3 on 2022-07-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0145_alter_works_times_end_alter_works_times_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='times_start',
            new_name='times',
        ),
        migrations.RemoveField(
            model_name='works',
            name='times_end',
        ),
    ]
