# Generated by Django 4.0.3 on 2022-07-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0146_rename_times_start_works_times_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='times',
            new_name='timesstart',
        ),
    ]
