# Generated by Django 4.0.3 on 2022-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0147_rename_times_works_timesstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='timesend',
            field=models.TextField(max_length=300, null=True, verbose_name='Время работы конец'),
        ),
    ]
