# Generated by Django 4.0.3 on 2022-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0148_works_timesend'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='obr',
            field=models.CharField(max_length=30, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='works',
            name='zp',
            field=models.CharField(max_length=30, null=True, verbose_name='Зарплата'),
        ),
    ]
