# Generated by Django 4.0.3 on 2022-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0149_works_obr_works_zp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='obr',
            field=models.CharField(max_length=100, null=True, verbose_name='Образование'),
        ),
    ]
