# Generated by Django 4.0.3 on 2022-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0151_works_opwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='graf',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='График'),
        ),
    ]
