# Generated by Django 4.0.3 on 2022-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0152_works_graf'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
