# Generated by Django 4.0.3 on 2022-08-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0153_locations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment_man',
            field=models.TextField(max_length=300, null=True, verbose_name='Коментарий менеджера'),
        ),
    ]
