# Generated by Django 4.0.3 on 2022-08-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0154_orders_comment_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='shopproiz',
            field=models.SlugField(max_length=200, null=True, verbose_name='Магазин произвольный'),
        ),
    ]
