# Generated by Django 4.0.3 on 2022-08-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0155_works_shopproiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezh',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='rezh',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
    ]
