# Generated by Django 4.0.3 on 2022-08-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0156_rezh_artikul_rezh_fileart'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='arti',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='arti_p',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='artiobschepit',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='artiobschepit',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='bogdan',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='bugalysh',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='bugalysh',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='chetkarino',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='krasnoufimsk',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='krasnoufimsk',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='pokrovskoe',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='pokrovskoe',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='product',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='shalinsk',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
        migrations.AddField(
            model_name='zajkovskoe',
            name='artikul',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='zajkovskoe',
            name='fileart',
            field=models.FileField(blank=True, null=True, upload_to='rezh/', verbose_name='Файл выгрузки товаров'),
        ),
    ]
