# Generated by Django 4.0.3 on 2022-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0157_arti_artikul_arti_fileart_arti_p_artikul_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zajkovskoe',
            name='fileart',
        ),
        migrations.CreateModel(
            name='filezajkovskoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileart', models.FileField(blank=True, null=True, upload_to='zajkovskoe', verbose_name='Файл выгрузки товаров')),
            ],
            options={
                'verbose_name': 'Зайковское сельпо file',
                'verbose_name_plural': 'Зайковское сельпо file',
                'ordering': ('fileart',),
                'index_together': {('id',)},
            },
        ),
    ]
