# Generated by Django 4.0.3 on 2022-08-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0158_remove_zajkovskoe_fileart_filezajkovskoe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filezajkovskoe',
        ),
    ]
