# Generated by Django 4.0.3 on 2022-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0159_delete_filezajkovskoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arti',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='arti_p',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='artiobschepit',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='bogdan',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='bugalysh',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='chetkarino',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='krasnoufimsk',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='pokrovskoe',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='rezh',
            name='fileart',
        ),
        migrations.RemoveField(
            model_name='shalinsk',
            name='fileart',
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название файла')),
                ('name_file', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название организации')),
                ('fileart', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Файл выгрузки товаров')),
            ],
            options={
                'verbose_name': 'Файловая обработка',
                'verbose_name_plural': 'Файловая обработка',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
