# Generated by Django 4.0.3 on 2022-08-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0160_remove_arti_fileart_remove_arti_p_fileart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file',
        ),
    ]
