# Generated by Django 3.2.3 on 2021-08-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_product'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
